# Site settings
repository: itspriddle/recipes.priddle.xyz
title: Recipes
url: "https://recipes.priddle.xyz"
baseurl: ""

encoding: utf-8

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

# Timezone
timezone: 'America/New_York'

# Files to exclude
exclude:
  - .envrc
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - bin
  - images
  - recipes/TEMPLATE.md
  - vendor

# Jekyll Plugins
plugins:
  - jekyll-default-layout
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jemoji

# jekyll-titltes-from-headings config
titles_from_headings:
  enabled:     true
  strip_title: false
  collections: false

# Layout

# Sass setup
sass:
  sass_dir: stylesheets
  style: compressed

# Metadata
author:
  name: Josh Priddle
  email: jpriddle@me.com
  github: itspriddle
  twitter: itspriddle

# Colletctions
collections:
  recipes:
    output: true

include:
  - recipes
  - index.md

defaults:
  - scope:
      path: recipes
    values:
      layout: default
      recipe: true

